"""add url subject col to articles

Revision ID: 73e198f75d33
Revises: 43374a2feed3
Create Date: 2022-04-29 13:28:43.665417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e198f75d33'
down_revision = '43374a2feed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('url', sa.String(), nullable=False))
    op.add_column('articles', sa.Column('subject', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'subject')
    op.drop_column('articles', 'url')
    # ### end Alembic commands ###
